"""initial_schema

Revision ID: 3be48352d77e
Revises: 
Create Date: 2026-02-24 22:54:18.333072
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3be48352d77e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('google_place_id', sa.String(length=300), nullable=True),
    sa.Column('yelp_id', sa.String(length=300), nullable=True),
    sa.Column('slug', sa.String(length=600), nullable=False),
    sa.Column('has_dedicated_gf_menu', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gf_item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gluten_mentioned_on_menu', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id'),
    sa.UniqueConstraint('yelp_id')
    )
    op.create_index(op.f('ix_restaurants_gf_item_count'), 'restaurants', ['gf_item_count'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    op.create_table('generated_gf_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('sensitivity_profile', sa.String(length=50), nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('strict_celiac_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_gf_menus_restaurant_id'), 'generated_gf_menus', ['restaurant_id'], unique=False)
    op.create_table('menu_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('google', 'yelp', 'user_upload', name='photo_source_enum', create_constraint=True), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_photos_restaurant_id'), 'menu_photos', ['restaurant_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('source_photo_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cross_contact_risk', sa.Enum('none', 'low', 'high', name='cross_contact_risk_enum', create_constraint=True), server_default='high', nullable=False),
    sa.Column('gf_label_on_menu', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_photo_id'], ['menu_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_menu_photos_restaurant_id'), table_name='menu_photos')
    op.drop_table('menu_photos')
    op.drop_index(op.f('ix_generated_gf_menus_restaurant_id'), table_name='generated_gf_menus')
    op.drop_table('generated_gf_menus')
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_gf_item_count'), table_name='restaurants')
    op.drop_index('idx_restaurants_location', table_name='restaurants', postgresql_using='gist')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
